### ISSUE TITLE
setetherbase still exists ?

### ISSUE THREAD

**Issue by euri10** [pipermerriam/web3.py#118]
- Version: all
- Python: 2.7/3.4/3.5
- OS: osx/linux/win
### What was wrong?

I dont know if I look at a deprecated wiki or if this function still exist, I cant find it in web3.js

https://github.com/ethereum/go-ethereum/wiki/JavaScript-Console#minersetetherbase

if it still exist it's not implemented, but I guess it doesnt and this is rather confusing to read old wikis ;)
#### Cute Animal Picture

![Cute animal picture](http://vignette4.wikia.nocookie.net/disney/images/8/8d/Lotso-angry.jpg/revision/latest?cb=20140127170152)

**Comment by pipermerriam** [comment]
If this option still exists in `go-ethereum` I'm fine adding this method.
