### ISSUE TITLE
Wrong owner address while using py.test

### ISSUE THREAD

**Issue by rotarui** [pipermerriam/web3.py#124]
### What was wrong?
Hi,
Tried to deploy a very simple contract (divided in two files), with an owner variable (`owner = msg.sender`).
The problem is that when I launch some tests, the returned value is not the good one (checked on etherscan for the contract owner ad it's good). 
I created a getter function that just returns an `adress` type variable . I am of course returning `owner`.
So I was wondering , is returning an address from a contract going to be well interpreted by python (address -> string) ? Or do I have a weird problem here ?

Thanks !

#### Cute Animal Picture

![Cute animal picture]()

**Comment by pipermerriam** [comment]
Can you provide me with some additional information like the code you are
using to check the address?

**Comment by rotarui** [comment]
Omg I just posted on the wrong github repo. I feel so stupid I wanted to post on populus one but got confused in all my tabs x). Searching how to delete now.

Sorry sorry

**Comment by pipermerriam** [comment]
No worries.
