### ISSUE TITLE
How to react to an unreachable node when dealing with filters

### ISSUE THREAD

**Issue by berndbohmeier** [pipermerriam/web3.py#126]
* Version: 3.1.1
* Python: 2.7
* OS: linux

### What was wrong?
If I have a server running that gets events from a node with the contract.on method, it seems that if it fails because the node is currently not available, it is dead forever and I have no way of reacting to that. 

see traceback: 
```
Traceback (most recent call last):
  File ".../local/lib/python2.7/site-packages/gevent/greenlet.py", line 534, in run
    result = self._run(*self.args, **self.kwargs)
  File ".../local/lib/python2.7/site-packages/web3/utils/filters.py", line 80, in _run
    changes = self.web3.eth.getFilterChanges(self.filter_id)
  File ".../local/lib/python2.7/site-packages/web3/utils/functional.py", line 22, in inner
    value = fn(*args, **kwargs)
  File ".../local/lib/python2.7/site-packages/web3/eth.py", line 310, in getFilterChanges
    "eth_getFilterChanges", [filter_id],
....
, in _create_socket
    raise first_error
error: [Errno 111] Connection refused
<LogFilter at 0x7fef3bfd9870> failed with error
```
I think it should reconnect and work again a soon as the nodes is available again, or there should be an easy way (maybe I am just not aware of it?) to react to this and reconnect in the application code, but I don't know how to do that because it runs in a Greenlet, so I don't know how to catch the Exception. 

Thanks for the help.

#### Cute Animal Picture

![Cute animal picture](https://thaowlblog.files.wordpress.com/2016/03/funny-beaver-cute-hands-up.jpg?w=700)

**Comment by pipermerriam** [comment]
I think this would be a great feature.  This could be implemented at either
the manage/provider layer or directly at the filter class. I lean towards
the latter.

**Comment by pipermerriam** [comment]
Also. Fantastic cute animal picture.

**Comment by berndbohmeier** [comment]
I just saw that Filter is a Greenlet, so it could probably be done in the application with `Greenlet.link_exception(callback)`, but I'd like it more to be handled by web3.

**Comment by pipermerriam** [comment]
@berndbohmeier if you are interested in taking a stab at this I'm more than happy to support you in whatever ways I can.  Otherwise this is going to be on the backburner for a bit as I'm focused pretty heavily elsewhere trying to get package management established in the ethereum ecosystem.

**Comment by pipermerriam** [comment]
Oh, and as far as implementing this with the `Greenlet` API, I think I'd like to steer away from that.  Gevent doesn't really play nice with others and thus there is a planned feature to be able to configure web3 to use either Gevent or native threading and so I'm trying to avoid any more code that is directly dependent on Gevent specific things.

**Comment by berndbohmeier** [comment]
I was able to implement it in the application logic for now with the Greenlet api, so it is not urgent. I might look into it.

**Comment by carver** [comment]
Closing as stale. We should consider this "reconnect to unreachable node" scenario when implementing #294, though.
