### ISSUE TITLE
Bug in calling methods automatically generated by solidity for public contract attributes

### ISSUE THREAD

**Issue by gkapkowski** [pipermerriam/web3.py#127]
* Version: 656903b34473a8cb658996a3dd8877ad9c734a12 (current master)
* Python: 2.7/3.4/3.5
* OS: osx/linux/win

### What was wrong?
For solidity code:
```
contract A {
    mapping (address => bytes32[]) public somename;
}
```
solc will generate function with ABI:
```
{
            "constant": True,
            "inputs": [
                {
                    "name": "",
                    "type": "address"
                },
                {
                    "name": "",
                    "type": "uint256"
                }
            ],
            "name": "somename",
            "outputs": [
                {
                    "name": "",
                    "type": "bytes32",
                    "value": "0x"
                }
            ],
            "payable": False,
            "type": "function"
        },
```
Notice that both `name` keys of inputs are empty.

The code in https://github.com/pipermerriam/web3.py/blob/master/web3/utils/abi.py#L162
Will squash two arguments pased to Contract.call().somename(addr, index) into one argument because it uses name as unique identifier. 

(Note, above examples are edited from my code so I haven't actually compile this exact code to reproduce the issue)

#### Cute Animal Picture

![Cute animal picture]()

**Comment by pipermerriam** [comment]
Good find. Thank you for reporting this.

**Comment by carver** [comment]
If the problem persists, please reopen the issue.
