### ISSUE TITLE
Question On Process

### ISSUE THREAD

**Issue by raymondcarl** [pipermerriam/web3.py#133]
Hi,

I was interested in adding more of the Web3 functionalities.  I'm not a developer and just wanted to ask a basic question.  Is it fair to say that the web3.py package formats requests into JSON RPC requests and passes onto a running ethereum node?  I tried to go through the source code, but it seems like there's a lot of abstraction taking place through a package that's imported (which also seems to be labelled "web3").

If the above is true, I also struggled to see where the JSON RPC request is actually being formed.

Sorry, no cute animal pictures as this is a question rather than a pull request.

**Comment by pipermerriam** [comment]
Good questions.  You are correct that there are two layers of abstraction in place.  Those layers came from the original design of the javascript web3 library but have proven to be good abstractions thus far.

The innermost layer is the *Provider*.  Providers have a specific communication channel with the Ethereum network such as an HTTP based JSON RPC server or the IPC Socket based RPC server.  Providers contain the necessary code to format and dispatch an RPC request and then handle the response.

The *Manager* abstraction manages the provider.  The default manager is very simple and doesn't do very much.  The reason for the manager abstraction is for more complex scenarios where you might want to delegate transaction signing to one provider but all other functionality to another.  There are two such managers in the current codebase.

All of this code can be found here: https://github.com/pipermerriam/web3.py/tree/master/web3/providers

**Comment by raymondcarl** [comment]
ahhhhhhh now I got it.  Thanks!
