### ISSUE TITLE
Web3 depends on testrpc.rpc 

### ISSUE THREAD

**Issue by chfast** [pipermerriam/web3.py#140]
* Version: 3.4.1
* Python: 2.7/3.4/3.5
* OS: win

### What was wrong?

The main web3 now depens on testrpc.rpc package, not even listed in requirements. So firstly web3 cannot be used without installing additional eth-testrpc. Moreover, eth-testrpc is not installable on Windows so we are all f*cked.

#### Cute Animal Picture

![Cute animal picture](http://img.hdwallpaperpc.com/cover/115/Animals_Other_cute_baby_duck_hd_little_Yellow_animal_Bird_swim_Water_HD_114430_detail_thumb.jpg)

**Comment by pipermerriam** [comment]
This is a bug.  I'll get a release out here to fix it.

**Comment by pipermerriam** [comment]
`3.4.2` is up on pypi and in the releases section here and fixes this issue.
