### ISSUE TITLE
-1 on int8 weird value

### ISSUE THREAD

**Issue by onepix** [pipermerriam/web3.py#144]
* Version: 3.4.4
* Python: 2.7.10
* OS: osx

### What was wrong?

Assuming that "-1" can be represented by the int8 type (range -128;+127) I have this contract
```
contract Example {
    int8 myInt = -1;

    function getMyInt() constant returns (int8) {
        return myInt;
    }

    function getMyLittleInt() constant returns (int8 myLittleInt) {
        myLittleInt = -1;
    }
}
```
then I get an "instance" of this with web3.py and try to retrieve it but this is what I get :  
```
>>> abi = json.loads('[{"constant":true,"inputs":[],"name":"getMyInt","outputs":[{"name":"","type":"int8"}],"payable":false,"type":"function"},{"constant":true,"inputs":[],"name":"getMyLittleInt","outputs":[{"name":"myLittleInt","type":"int8"}],"payable":false,"type":"function"}]')
>>> myIntContract = web3.eth.contract(abi, address="0x1d4e3694b0155bf821963793ecac3b84f4a0815f")
>>> myIntContract
<web3.contract.Contract object at 0x1075a6290>
>>> myIntContract.call().getMyInt()
115792089237316195423570985008687907853269984665640564039457584007913129639679L
>>> myIntContract.call().getMyLittleInt()
115792089237316195423570985008687907853269984665640564039457584007913129639679L
```

Is that right ? What's wrong ?

#### Cute Animal Picture

![Cute animal picture](http://10wallpaper.com/wallpaper/medium/1109/baby_seal-Animal_World_Series_Wallpaper_medium.jpg)

**Comment by pipermerriam** [comment]
That is exceptionally odd and definitely a bug.  I'll try to look into this soon.

**Comment by onepix** [comment]
Thanks ! 
I suppose it will not help that much but I encountered the same issue with the other python ethereum client named _ethjsonrpc_ and by changing the type directly into the ABI from int8 to int256 I got `-1L`

**Comment by pipermerriam** [comment]
It is looking alot like this is a bug in the pyethereum codebase combined with a validation bug in the `eth-abi-utils` codebase.  I *could* fix this on the `eth-abi-utils` side by just truncating the output but that feels wrong.  Going to think on this for a few days before deciding a course of action.  I think this bug is going to exist on *all* negative non 256 bit signed integer values

**Comment by pipermerriam** [comment]
This was fixed in the underlying ABI utils library.
