### ISSUE TITLE
No connection reuse

### ISSUE THREAD

**Issue by holiman** [pipermerriam/web3.py#152]
* Version: 3.5.2 Release
* Python: 2.7
* OS: alpine linux within Docker 

### What was wrong?

I was using web3.py within Hive, basically it's run within a docker container and performs various queries against a client. 

In one of the tests, I'm verifying a lot of conditions, ~30K. After `28232` requests, the lib failed with the following exception : `requests.packages.urllib3.connection.HTTPConnection object at 0x7f4b0a86a750\u003e: Failed to establish a new connection: [Errno 99] Address not available` 

@karalabe pointed out that `28232` == `61000`- `32768`. That is; I was exhausing all the TCP ports linux lets me use for outbound connections. 

According to `requests` docs: http://docs.python-requests.org/en/master/user/advanced/#keep-alive: 

> Excellent news — thanks to urllib3, keep-alive is 100% automatic within a session! Any requests that you make within a session will automatically reuse the appropriate connection!

However, the library does not use a session: 

https://github.com/pipermerriam/web3.py/blob/master/web3/utils/compat/compat_requests.py#L6

```python

def make_post_request(endpoint_uri, data, *args, **kwargs):
    kwargs.setdefault('timeout', 10)
    response = requests.post(endpoint_uri, data=data, *args, **kwargs)
```

In my case, I only really need a couple of the methods, and it was simple enough to implement these myself using a requests, skipping web3.py altogethere. But it may be an idea to add support for this kind of usecase anyway, since connection reuse also adds a bit of speed, and the library is likely to use the same endpoint over and over again. 

With my session-based thingy, the problem went away. 

#### Cute Animal Picture
![piper](https://cloud.githubusercontent.com/assets/142290/22542428/051f7888-e92c-11e6-90bd-84a0476f33ba.png)

He's a bit disappointed right now

**Comment by pipermerriam** [comment]
Should be fixed in `3.5.3` which is on pypi and the releases section of this repo.
