### ISSUE TITLE
Non-helpful error message when calling contract on unsynced chain

### ISSUE THREAD

**Issue by ice09** [pipermerriam/web3.py#161]
* Version: 3.6.2
* Python: 2.7
* OS: linux

### What was wrong?

After initializing web3 against a local, unsynced ropsten chain, a new contract could not be called, eg. by `con.call().get()`. This is correct behaviour, but the error message:

`BadFunctionCallOutput: Could not decode contract function call get return data 0x for output_types [u'string']`

is not helpful and does not indicate where to look for an error.
Better would be something like 

`BadFunctionCallOutput: Could not transact with/call contract function, is contract deployed correctly and chain synced?`

#### Cute Animal Picture

![Cute animal picture]()

**Comment by pipermerriam** [comment]
This should be a simple thing to add.

https://github.com/pipermerriam/web3.py/blob/master/web3/contract.py#L766

At that point, within the exception handling we can check whether the response was `0x`, aka empty string, and if that is the case we can check whether there is any code (using `eth_getCode`) at the contract address.  If both return true, raise a different error indicating that a function was called on an address with no code.

**Comment by Gingko925** [comment]
Have you solved this problem? I faced the same one.

**Comment by pipermerriam** [comment]
It hasn't been solved *but* it will be soon.

**Comment by pipermerriam** [comment]
Fixed in #207

**Comment by kivo360** [comment]
I'm getting the same error. The main problems is that I see the abi of the contract, yet I can't access the method.
