### ISSUE TITLE
Implement support for "function" abi type

### ISSUE THREAD

**Issue by ericssonaxel** [pipermerriam/web3.py#164]
* Version: 3.6.1
* Pyhon: 2.7
* OS: macOS

### What was wrong?
In (https://github.com/ethereum/solidity/pull/1122) a "function" abi type was added. This is not yet implemented in web3.py

Example:
In my_contract:
`
function truebool(address a) external constant returns (bool){ return true;}`

`
function get_function() external constant returns(
function(address) external constant returns(bool)
){ return (this.truebool); }`

In python:
`
func = my_contract.call().get_function() #returns function type
my_other_contract.transact({...}).other_function(func) #expects function type as arg`

Currently, func will have value `None`. It seems like the function type is similar to bytes24 per (http://solidity.readthedocs.io/en/develop/types.html) under function types. 

It is possible to trick web3.py to return the function by changing the output type to "bytes24" in the abi for the contract, but this doesn't seem to work for input types; parity gives a **Transaction execution error** when trying to call `other_function(func)`.

#### Cute Animal Picture
![cute-polar-bear](https://cloud.githubusercontent.com/assets/3268707/23246669/28e1c4b4-f94a-11e6-8e72-bbbe3b392634.jpg)

**Comment by ericssonaxel** [comment]
Pull request created -> 
https://github.com/pipermerriam/web3.py/pull/169
https://github.com/pipermerriam/ethereum-abi-utils/pull/12

**Comment by pipermerriam** [comment]
Merged via a different PR.  Web3 will need to bump its requirement to `ethereum-abi-utils>=0.4.1`.

**Comment by carver** [comment]
Version bump in #322
