### ISSUE TITLE
Online docs shows wrong keyword for event filters

### ISSUE THREAD

**Issue by davebryson** [pipermerriam/web3.py#168]
* Version: 2.4.0

This is a trivial documentation thing in reference to the online docs:
http://web3py.readthedocs.io/en/latest/contracts.html#events  Just adding it here in case someone else runs into the same problem.

The document reference `filters` and the example shows:

`transfer_filter = my_token_contract.on('Transfer', {'filters': {'_from': '0xdc3a9db694bcdd55ebae4a89b22ac6d12b3f0c24'}})`

But it appears instead of `filters` it should be `filter`.   Using the plural form gave an error - `filter` appears to be the right key name

**Comment by youmind** [comment]
with what is problem now?
