### ISSUE TITLE
Windows IPC/Named pipe does not work

### ISSUE THREAD

**Issue by hzman** [pipermerriam/web3.py#17]
Right now web3.py use sockets on GNU/Linux to connect to the IPC. This wont work on Windows since named pipes on windows does not make use of sockets. From what google says you can use a simple file handle to write and read on the named pipe (\.\pipe\geth.ipc). I have tried using simple popen/open to read and write data, but no luck. 

I have also tried to use this library for python, http://docs.activestate.com/activepython/2.6/pywin32/win32file.html

Next step is to check how the JS-version of web3 is connecting to the named pipe, but i can imagine that it uses a more low level connection directly via ethereum code base.

**Comment by void4** [comment]
Thank you for investigating this. I don't use Windows myself and therefore can't test it. If you find a solution, feel free to submit a pull request.
