### ISSUE TITLE
Support rlp==0.4.7

### ISSUE THREAD

**Issue by karlfloersch** [pipermerriam/web3.py#170]
* Version: 3.7.2
* Python: 2.7
* OS: osx

### What was wrong?
https://github.com/ethereum/pydevp2p requires `rlp==0.4.7` ([here](https://github.com/ethereum/pydevp2p/blob/develop/requirements.txt#L11)), but `web3.py` requires `rlp>=0.4.6,<0.4.7`. This causes headaches when a project requires both packages as well as `rlp` independently.

I've created a repo with updated requirements here: https://github.com/karlfloersch/web3.py, but I haven't verified that everything is working properly.

#### Cute Animal Picture

![Cute animal picture](http://cdn.9appsdownloading.com/group1/M01/E8/54/pYYBAFbW5uiAUpNuAACUkuW7ZCQ868.png)
Thank you!

**Comment by pipermerriam** [comment]
`3.8.0` is now available which now pins `rlp>=0.4.7`.  If you are also using `eth-testrpc` you should update to `1.2.0` as well.

**Comment by karlfloersch** [comment]
Awesome thank you! 😄
