### ISSUE TITLE
web3 error on raspberry pi 

### ISSUE THREAD

**Issue by bellaj** [pipermerriam/web3.py#173]
Hi,

I've installed web3.py on the raspberry pi 2 (from source after the installation of the requirements) but when i run a snipet code i get this error

`ImportError: cannot import name Web3`

*NB: If i run the code in the web.py it works

**Comment by bellaj** [comment]
solution : 

import sys
sys.path.append('/path to web3/')

don't name your snipet code web3.py

**Comment by pipermerriam** [comment]
@bellaj alternatively you can put a `from __future__ import absolute_import` in python 2.7 and it will fix this annoying import behavior from python 2.  Alternatively you can switch to python3 as well (which you should do anyways 😈 )
