### ISSUE TITLE
ImportError: No module named eth_utils

### ISSUE THREAD

**Issue by agatsoh** [pipermerriam/web3.py#180]
* Version: 
```
pip show web3
Name: web3
Version: 2.8.1
Summary: Web3.py
Home-page: https://github.com/pipermerriam/web3.py
Author: Piper Merriam
Author-email: pipermerriam@gmail.com
License: MIT
Location: /home/krishna/web3.py
Requires: pysha3, rlp, gevent, geventhttpclient, ethereum-abi-utils, pysha3
```

* Python: 2.7

* OS: linux(Ubuntu)

### What was wrong?
Import Error
```
In [1]: from web3 import Web3
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-898ce11db109> in <module>()
----> 1 from web3 import Web3

/home/krishna/web3.py/web3/__init__.py in <module>()
      3 import pkg_resources
      4 
----> 5 from web3.main import Web3
      6 from web3.providers.rpc import (
      7     HTTPProvider,

/home/krishna/web3.py/web3/main.py in <module>()
      1 from __future__ import absolute_import
      2 
----> 3 from eth_utils import (
      4     to_wei,
      5     from_wei,

ImportError: No module named eth_utils

```

#### Cute Animal Picture

![Cute animal picture]()
![image](https://cloud.githubusercontent.com/assets/15123108/25709783/e43dbe58-3107-11e7-9166-61ce013c7304.png)

**Comment by cle1000** [comment]
```pip install -r requirements-dev.txt ```

**Comment by agatsoh** [comment]
I already tried this, it does not work for me. Worth noting I am doing a `pip install web3`  actually 
or should do a  `python setup.py install`

**Comment by agatsoh** [comment]
Ok I did a `python setup.py install` and it installed the latest `3.8.1` for me and the problem got solved. So this problem comes only in the pip version.

**Comment by pipermerriam** [comment]
I tested this with a fresh install with `pip install web3` and everything seems to be working.  I'm guessing there was an issue with your local environment.
