### ISSUE TITLE
Error: VM Exception while executing eth_estimateGas: invalid opcode

### ISSUE THREAD

**Issue by jeanjluo** [pipermerriam/web3.py#186]
* Version: 3.9.1
* py-solc: 1.0.1
* testrpc: 3.0.5
* Python: 3.5
* OS: ubuntu 16.04

I am getting the "Error: VM Exception while executing eth_estimateGas: invalid opcode" error when deploying a contract.

Code:
```source_code = 'contract MyToken {     address issuer;     mapping (address => uint) balances;      event Issue(address account, uint amount);     event Transfer(address from, address to, uint amount);      function MyToken() {         issuer = msg.sender;     }      function issue(address account, uint amount) {         if (msg.sender != issuer) throw;         balances[account] += amount;     }      function transfer(address to, uint amount) {         if (balances[msg.sender] < amount) throw;          balances[msg.sender] -= amount;         balances[to] += amount;          Transfer(msg.sender, to, amount);     }      function getBalance(address account) constant returns (uint) {         return balances[account];     } }'

from web3 import Web3 
web3 = Web3(Web3.HTTPProvider('http://127.0.0.1:8545'))

from solc import compile_source
compile_sol = compile_source(source_code)

MyContract = web3.eth.contract(
    abi = compile_sol['<stdin>:MyToken']['abi'],
    bytecode = compile_sol['<stdin>:MyToken']['bin'],   
    bytecode_runtime = compile_sol['<stdin>:MyToken']['bin-runtime']
)
 
trans_hash = MyContract.deploy(transaction={'from':web3.eth.accounts[0],'value':120})
```
Error message:
> Traceback (most recent call last):
>   File "deploy.py", line 42, in <module>
>     trans_hash = MyContract.deploy(transaction={'from':web3.eth.accounts[0],'value':120})
>   File "/usr/local/lib/python3.5/dist-packages/web3/contract.py", line 298, in deploy
>     txn_hash = cls.web3.eth.sendTransaction(deploy_transaction)
>   File "/usr/local/lib/python3.5/dist-packages/eth_utils/string.py", line 85, in inner
>     return force_obj_to_text(fn(*args, **kwargs))
>   File "/usr/local/lib/python3.5/dist-packages/web3/eth.py", line 239, in sendTransaction
>     transaction=formatted_transaction,
>   File "/usr/local/lib/python3.5/dist-packages/web3/utils/transactions.py", line 47, in get_buffered_gas_estimate
>     gas_estimate = web3.eth.estimateGas(gas_estimate_transaction)
>   File "/usr/local/lib/python3.5/dist-packages/web3/utils/functional.py", line 14, in inner
>     value = fn(*args, **kwargs)
>   File "/usr/local/lib/python3.5/dist-packages/web3/eth.py", line 279, in estimateGas
>     [formatted_transaction],
>   File "/usr/local/lib/python3.5/dist-packages/web3/providers/manager.py", line 35, in request_blocking
>     raise ValueError(response["error"])
> ValueError: {'code': -32000, 'message': 'Error: VM Exception while executing eth_estimateGas: invalid opcode\n    at /usr/lib/node_modules/ethereumjs-testrpc/node_modules/web3-provider-engine/subproviders/vm.js:117:17\n    at /usr/lib/node_modules/ethereumjs-testrpc/node_modules/ethereumjs-vm/lib/runTx.js:59:5\n    at /usr/lib/node_modules/ethereumjs-testrpc/node_modules/ethereumjs-vm/node_modules/async/dist/async.js:3838:9\n    at /usr/lib/node_modules/ethereumjs-testrpc/node_modules/ethereumjs-vm/node_modules/async/dist/async.js:421:16\n    at replenish (/usr/lib/node_modules/ethereumjs-testrpc/node_modules/ethereumjs-vm/node_modules/async/dist/async.js:941:25)\n    at iterateeCallback (/usr/lib/node_modules/ethereumjs-testrpc/node_modules/ethereumjs-vm/node_modules/async/dist/async.js:931:17)\n    at /usr/lib/node_modules/ethereumjs-testrpc/node_modules/ethereumjs-vm/node_modules/async/dist/async.js:906:16\n    at /usr/lib/node_modules/ethereumjs-testrpc/node_modules/ethereumjs-vm/node_modules/async/dist/async.js:3835:13\n    at /usr/lib/node_modules/ethereumjs-testrpc/node_modules/ethereumjs-vm/lib/runTx.js:55:9\n    at /usr/lib/node_modules/ethereumjs-testrpc/node_modules/ethereumjs-vm/lib/cache.js:107:7'}

**Comment by jeanjluo** [comment]
Just figured out it is an issue with the contract

**Comment by PavelPolyakov** [comment]
Hi @jeanjluo ,

I also experience issues with my contract (I believe).

In particular get the same `VM Exception while executing eth_estimateGas: invalid opcode` error.
Any hints what exactly was wrong in your contract? And how you managed to debug it?

Regards,
