### ISSUE TITLE
Contract function bytes encoding

### ISSUE THREAD

**Issue by TrekDev** [pipermerriam/web3.py#189]
* Version: latest pip release
* Python: 3.5
* OS: linux

### What was wrong?
I have a contract that returns bytes (in this case an IPFS address). The type returned in python is a string and I can't figure out the encoding:

```
        addr = myContract.call().getAddress(x) // function getAddress(uint x) constant returns (bytes)
        print(type(addr)) // prints: <class 'str'>
        print(addr) // prints: ÉÔ>;X¼|tà¬Z¸Lâ­F+w¥4ï¾
```

How can I get addr as a bytearray/bytes so I can base58 encode it (ie. "Qm...")? I've tried converting with bytes(addr) and encoding in base58 but I can't seem to correctly decode the string encoding as returned from web3.py.

**Comment by veox** [comment]
> Version: latest pip release

v3.8.1? Please be explicit, three months from now "latest" could change.

I've also experienced this, [in this test case](https://gitlab.com/veox/ens-bugbounty/blob/1cf4bb10d082e5da63fcf1edcb1fa1cff269caf4/tests/test_hashregsimplified.py#L199) I think.

Haven't had time to dig for cause yet.

**Comment by pipermerriam** [comment]
@TrekDev 

try using this utility.

```python
from eth_utils import force_bytes
force_bytes(the_value)
```

Internally populus uses the `force_bytes` and `force_text` utility functions from `eth_utils` for casting things to/from bytes/text

Let me know if you are still having problems.

**Comment by veox** [comment]
It seems both @TrekDev and I were expecting a call like that would perform type deduction behind the curtain.

The [docs for this method](https://web3py.readthedocs.io/en/latest/contracts.html#web3.contract.Contract.call) seem to suggest that it does, at least for Solidity functions that return `uint`.

Maybe a note on type deduction (or lack of any such guarantees) is in order.

**Comment by pipermerriam** [comment]
I think this is a reasonable change to the API.  Currently, all of the `bytesXX`, `string` and `bytes` types will be returned as text (not bytes) strings.  Seems appropriate to modify this to return them as bytes since that format is canonical and not subject to trying to infer how they are encoded.  Will open a new issue for this.

**Comment by veox** [comment]
goto: #193
