### ISSUE TITLE
Trying to Troubleshoot a Problem Between Either Requests, Web3py, or Parity

### ISSUE THREAD

**Issue by raymondcarl** [pipermerriam/web3.py#190]
* Version: 3.8.0
* Python: 2.7
* OS: linux

### What was wrong?
I get an error when I try to extract transaction data using Web3Py.  The error is:  `requests.exceptions.ReadTimeout` (full error is at the bottom)

Code:
```python
import pandas as pd
import multiprocessing as mp
from itertools import combinations
from web3 import Web3, KeepAliveRPCProvider, IPCProvider

def check_data(arg):
	web3 = Web3(KeepAliveRPCProvider(host= '10.132.0.14', port='8545'))
	transactions = web3.eth.getBlock(arg)[u'transactions']
	return transactions

iterate_1 = range(0,100000)

results = map(check_data, iterate_1)
```

I've done many things to isolate the error.  I do not remember which version I was using, but this seemed to work OK when running back in January.  Now, I'm getting an error every 2-5 times I execute this code.  Originally, I thought the requests error was from the Pymongo package, but I took it out and discovered that the problem was still there.

**Things I've done:**

1. Try the same thing on a Geth node instead of a parity node:  request error still there.
2. Use the Node.js Web3 pakage instead of Web3Py:  Waiting on results from that
3. Using a local network machine to run geth / parity:  that seemed to reduce the frequency of the error, but still there.
4.  Maybe this was "overload" for both a geth or parity node?  So, I tried to alternate between 2 different parity nodes.  Error was still there.
5.  Somewhere on stackoverflow... someone suggested to put a brief pause.  That did not help.
6.  Above was originally part of a parallel process.  Removed the multiprocessing package and just use 1 core.  Problem still there.

That leads me to believe it's something wrong with the Requests package in python (which is what I assume that makes the call to the ethereum client), Web3Py, or could even still be a problem with both Geth and Parity.

My bet is that it's something with the request package, but any steps to further troubleshoot this issue are highly appreciated.  I saw a few similar issues with that package, but nothing with the same circumstances as mine.  Most were related to wrong http headers, etc.  If that were the case here, I would expect for it to never work versus working every 3-5 times.

This problem has been driving be nuts for 4 days ARRRRGGGGH!!!

I was thinking about trying to check the requests on the geth / parity server, but I don't really know how, and I think it would be tough to find given the number of requests I am bombarding the node with per a second.

**Full Error Message**
```
Traceback (most recent call last):
  File "test2.py", line 26, in <module>
    results = map(check_data, iterate_1)
  File "test2.py", line 21, in check_data
    transactions = web3.eth.getBlock(arg)[u'transactions']
  File "/home/raymond_carl/anaconda2/lib/python2.7/site-packages/web3/utils/functional.py", line 14, in inner
    value = fn(*args, **kwargs)
  File "/home/raymond_carl/anaconda2/lib/python2.7/site-packages/web3/eth.py", line 163, in getBlock
    full_transactions,
  File "/home/raymond_carl/anaconda2/lib/python2.7/site-packages/web3/providers/manager.py", line 44, in request_blocking
    response_raw = self.provider.make_request(method, params)
  File "/home/raymond_carl/anaconda2/lib/python2.7/site-packages/web3/providers/rpc.py", line 52, in make_request
    **self.get_request_kwargs()
  File "/home/raymond_carl/anaconda2/lib/python2.7/site-packages/web3/utils/compat/compat_requests.py", line 21, in make_post_request
    response = session.post(endpoint_uri, data=data, *args, **kwargs)
  File "/home/raymond_carl/anaconda2/lib/python2.7/site-packages/requests/sessions.py", line 535, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/home/raymond_carl/anaconda2/lib/python2.7/site-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/raymond_carl/anaconda2/lib/python2.7/site-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/home/raymond_carl/anaconda2/lib/python2.7/site-packages/requests/adapters.py", line 499, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='10.132.0.14', port=8545): Read timed out. (read timeout=10)
```

#### Cute Animal Picture
This is our cat Bella hiding in the sofa...
![img_1315](https://user-images.githubusercontent.com/9866425/27554180-df960f2a-5aad-11e7-8003-c9642f675a11.JPG)

**Comment by raymondcarl** [comment]
Forgot to mention 2 things:

1. Purpose I'm doing this:  trying to get the full list of all transaction hash and (then) the transaction data.
2. This also could've happened previously when I thought that it was working back in January, but I noticed today that I think imap() in the multiprocessing might bury errors.... Seems strange, but there were some errors I didn't noticed until I started using map.

**Comment by pipermerriam** [comment]
What I *think* is happening is that your parity/geth node is taking a long time to respond to the request and thus, the request is timing out.  I have two things I'd suggest you try.

1. Instead of using the `KeepAliveRPCProvider` switch to use the `HTTPProvider`.  You'll need to change how you instantiate the provider to the following.  This is largely a superficial change but it should save you some headache updating your code down the road when `KeepAliveRPCProvider` and `RPCProvider` are removed from the codebase (as they were previously deprecated).

```python
web3 = Web3(KeepAliveRPCProvider('http://10.132.0.14:8545'))
```

2. Change the way you are instantiating the provider to increase the timeout used by requests.

```
web3 = Web3(KeepAliveRPCProvider('http://10.132.0.14:8545', request_kwargs={'timeout': 60}))
```

The code above would increase the timeout to 60 seconds (up from the 10 second default).


*if* this turns out to be the case, it may be worth examining both the hardware you are running your node on as well as the method you are using to make requests as it should not be taking 10 seconds to return from most RPC calls unless you are running on something underpowered like a rasberry pi.

**Comment by raymondcarl** [comment]
That could be it.  Despite the actual purpose Ethereum was created for, I run the nodes and application on Google Cloud.  I downsized the machine a few months ago.  I originally dismissed the idea that it was hardware related because I watched the CPU, RAM, and IOPS during the Web3Py process.  They all seemed OK and nothing was maxed out.  I was thinking there might be some cap on the max number of concurrent connections, and that maybe they haven't had enough time to close...

Anyhow.... I will switch to `HTTPProvider`, try a bigger machine, and see how it goes.

**Comment by raymondcarl** [comment]
@pipermerriam 

It seems to be working OK so far on a normal machine versus a tiny machine.  But I was paying closer attention to the parity node and I'm concerned that maybe too many connections are being left open.  Do you know if there is a need in Web3 to "close" a connection after you're done with it similar to what you would do for a database connection (mongoDB, MS SQL, etc.)?

<img width="898" alt="screen shot 2017-06-27 at 21 29 27" src="https://user-images.githubusercontent.com/9866425/27606302-08317398-5b80-11e7-9a44-b825d94ef499.png">

**Comment by pipermerriam** [comment]
It is quite possible that connections are being left open.  Most of my current web3 usage isn't long running so that may be why I haven't run into this issue.  I am going to close this for now but please re-open if this isn't resolved.

**Comment by raymondcarl** [comment]
@pipermerriam      I'm going to leave it closed.  I think in general, the multiprocessing package should probably be avoided with Web3, but I don't know enough to confirm.  By the way, could you run this command?  `web3.eth.getBlock(3853348)`

```
As far as I can see, my geth node is fully synced, but I get the following error for that block and every block after:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/raymond_carl/anaconda2/lib/python2.7/site-packages/web3/utils/functional.py", line 15, in inner
    return formatter(value)
  File "/home/raymond_carl/anaconda2/lib/python2.7/site-packages/eth_utils/functional.py", line 11, in <lambda>
    return lambda x: f(g(x))
  File "/home/raymond_carl/anaconda2/lib/python2.7/site-packages/eth_utils/string.py", line 85, in inner
    return force_obj_to_text(fn(*args, **kwargs))
  File "/home/raymond_carl/anaconda2/lib/python2.7/site-packages/web3/formatters.py", line 213, in output_block_formatter
    for key, value in block.items()
AttributeError: 'NoneType' object has no attribute 'items'
>>> 
```

**Comment by raymondcarl** [comment]
@pipermerriam   oh forgot to mention that I confirmed this:
```
>>> number = web3.eth.blockNumber                                                                                    
>>> number
3949289
```

**Comment by pipermerriam** [comment]
@raymondcarl regarding your previous error, I suspect that's due to connecting to a node that's not fully synced?

**Comment by raymondcarl** [comment]
@pipermerriam   yeah, I thought the same thing, but I was getting the response OK, for blocks starting at approximately 3.9 million.  Going to try it again today on a new node, but it was really strange.
