### ISSUE TITLE
Return `bytesXX`, `bytes` and `string` types as byte strings

### ISSUE THREAD

**Issue by pipermerriam** [pipermerriam/web3.py#193]
### What is wrong?

Currently, contract functions which return any of `bytesXX`, `string`, or `bytes` will have their values returned as text strings.  This is not intuitive as it requires the user to infer the proper encoding if they wish to perform some other conversion.

### How can it be fixed.

Change to return byte strings.

#### Where to start in the code

The `web3.contract.call_contract_function` function found @ https://github.com/pipermerriam/web3.py/blob/master/web3/contract.py#L744 will need to have the `force_return_to_text` decorator removed.

Once that is done, see which tests are failing should indicate if any additional changes need to be made.

**Comment by djrtwo** [comment]
Issue was resolved via this merged PR https://github.com/pipermerriam/web3.py/pull/197.
This can be closed

**Comment by djrtwo** [comment]
@pipermerriam Ping! This can be closed
