### ISSUE TITLE
Add checksum validation to address parameters.

### ISSUE THREAD

**Issue by pipermerriam** [pipermerriam/web3.py#203]
### What is wrong?

There are *many* methods in the Web3 api which take an address as an argument. When a [EIP55](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-55.md) checksummed address is passed into these functions, the checksum is not validated.  It should be.

### How can it be fixed?

In any place where a function or method takes an address an argument, that address should be checked using the following logic.

* If the value is not a recognized address format, validation is skipped
* If the value is not a 20-byte hex encoded string, validation is skipped
* If the hexidecimal portion of the value is all uppercase or all lowercase, validation is skipped
* If the hexidecimal portion contains both uppercase and lowercase letters, validation is performed using `eth_utils.is_checksum_address`

**Comment by pipermerriam** [comment]
If you upgrade the `ethereum-utils` requirement to `>=0.3.0` you can use the new [`is_checksum_formatted_address`](https://github.com/pipermerriam/ethereum-utils#is_checksum_formatted_addressvalue---bool) utility to check whether the value *looks* like a checksum address prior to validating the checksum with [`is_checksum_address`](https://github.com/pipermerriam/ethereum-utils#is_checksum_addressvalue---bool)

**Comment by djrtwo** [comment]
@pipermerriam Would this throw a ValueError?

**Comment by pipermerriam** [comment]
> Would this throw a ValueError?

Either `ValueError` or a new custom exception `ValidationError`.  I think I prefer defaulting to `ValueError` until we have an explicit need to catch this specific exception.

**Comment by pipermerriam** [comment]
Done in #206
