### ISSUE TITLE
Migrate from `eth_utils.compose` to `toolz.functoolz.compose` 

### ISSUE THREAD

**Issue by pipermerriam** [pipermerriam/web3.py#204]
### What is wrong?

The library currently uses the [`compose`](https://github.com/pipermerriam/ethereum-utils#composecallables---callable) function from the [`ethereum-utils`](https://github.com/pipermerriam/ethereum-utils) library.  This function has been deprecated as of `ethereum-utils>=0.3.0`

### How can it be fixed?

* Add the [`toolz`](http://toolz.readthedocs.io/en/latest/index.html) library to the web3.py dependencies in `setup.py`
* Change all places in `web3.py` that use `eth_utils.compose` to instead use `toolz.functoolz.compose`.

Note that these two functions do not behave the same.  The `eth_utils.compose` function applies the functions from left to right.  The `toolz.functoolz.compose` function applies the functions from right to left.  When swapping these out, care must be taken to reverse the order of the function composition to preserve the intended ordering.

**Comment by djrtwo** [comment]
Picking this up. going to knock this one out before 203

**Comment by pipermerriam** [comment]
done in #205
