### ISSUE TITLE
web3.personal.unlockAccount doesn't accept integer as unlock period parameter

### ISSUE THREAD

**Issue by userpasta** [pipermerriam/web3.py#214]
* Version: 3.9.0
* Python: 2.7
* OS: not platform specific 

### What was wrong?
Method web3.personal.unlockAccount doesn't accept integer as unlock period parameter.
Example:
`web3.personal.unlockAccount(eth_address, 'strongPassword', 10000)`
returns `ValueError`:
`ValueError: {u'message': u'invalid type: integer `10000`, expected a 0x-prefixed, hex-encoded number of type U128', u'code': -32602, u'data': None}`

when using value in HEX :
`web3.personal.unlockAccount(eth_address, 'strongPassword', 10000)`
it works fine (returns `True`)

**Comment by carver** [comment]
Presumably you meant that `web3.personal.unlockAccount(eth_address, 'strongPassword', '0x2710')` works as expected?

**Comment by userpasta** [comment]
Yes! Apologies, copy paste fail.

**Comment by djrtwo** [comment]
@userpasta I'm having trouble reproducing this error when connecting to a geth node. There is also a test in `test_personal_unlockAccount.py` that explicitly uses an integer argument. On top of that, I tried with a hex-string for duration parameter and got the following error 

```
web3.personal.unlockAccount(eth_address, 'strongPassword', "0x2710")

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "web3/personal.py", line 85, in unlockAccount
    [account, passphrase, duration],
  File "web3/manager.py", line 96, in request_blocking
    raise ValueError(response["error"])
ValueError: {u'message': u'invalid argument 2: json: cannot unmarshal string into Go value of type uint64', u'code': -32602}
```

What type of node are you connecting to? `geth`, `testrpc`, `parity`, etc...
Considering there is not explicit check in web3.py on the `duration` type and it is simply passed onto the provider, I'm guessing it has to do with a node implementation specific error.

**Comment by djrtwo** [comment]
@userpasta did you see my question above?

**Comment by carver** [comment]
@djrtwo were you manually testing at the v3.9.0 tag? Maybe it got fixed in a later version

**Comment by userpasta** [comment]
Apologies, was OoO. 
@djrtwo I'm connected to the parity node. I was testing in v3.9.0. It's not a issue for me to provide the number in hex, but it variable type wasn't consistent with web3js, that's why Piper recommended to file a bug.

Oh, so it's node specific. Looks like a false alarm, feel free to close the bug.

**Comment by shanefontaine** [comment]
@djrtwo @carver Did you find a workaround to this? I am having the same error on Parity.

**Comment by carver** [comment]
If this is a problem when connecting to parity, then we still need to fix it.

If this is a problem that's fixed when updating Web3 to v3.15.0, then we should close it.

@userpasta can you try updating web3 and running again?

**Comment by shanefontaine** [comment]
@carver It works with v3.15.0

**Comment by carver** [comment]
Thanks! Closing for now. Please reopen if you can reproduce on a recent version.
