### ISSUE TITLE
Create new `Web3.soliditySha3()` helper function

### ISSUE THREAD

**Issue by pipermerriam** [pipermerriam/web3.py#218]
### What is wrong

I can be useful to have a function which replicates the `sha3` functionality from solidity.

### How can it be implemented.

It needs to behave the same as `sha3` in solidity which means it needs to know the *types* for its inputs in order to properly pack the bytes representations correctly.  The following API should be sufficient.

```python
web3 = Web3(...)
web3.soliditySha3(['uint256', 'bytes', 'address[]'], [12345, b'a-byte-string', ['0xabcd1234...', '0x1234abcd...'])
```

**Comment by pipermerriam** [comment]
This isn't entirely easy pickins but it should be do-able by someone with a bit of domain knowledge.  I think using the existing js implementations of this method would be a good place to start figuring out the best way to implement it.

**Comment by djrtwo** [comment]
I'm looking into this.

A few questions:
- Would this live in main.py?
- Tests would be to get some real output from the solidity function and test again?
- Should it actually be called `keccak256` with `sha3` being an alias?

**Comment by djrtwo** [comment]
Planning on building out support for following types:
- 'bool'
- 'uint8' to 'uint256' in steps of 8
- 'address'
- 'bytes1', 'bytes2', ..., 'bytes32'
- 'bytes32.byte' (alias for bytes1)
- 'bytes'
- 'string'
- arrays of all acceptable types
- multidimensional arrays

Note: keccak of mapping looks currently unsupported in solidity
Attempted keccak256 on any type of mapping leads to similar error:
> UnimplementedFeatureError: Encoding type "mapping(address => bool)" not yet implemented.

**Comment by djrtwo** [comment]
@pipermerriam ready to close
