### ISSUE TITLE
isAddress() does not confirm the checksum

### ISSUE THREAD

**Issue by carver** [pipermerriam/web3.py#227]
* Version: 3.11.1
* Python: 3.5
* OS: linux

### What was wrong?

I expected an `isAddress()` call on an address with an invalid checksum to fail.

According to the [docs](http://web3py.readthedocs.io/en/latest/web3.main.html?highlight=checksum#web3.Web3.isAddress):
> If the address contains mixed upper and lower cased characters this function also checks if the the (sic) address checksum is valid according to EIP55

```
In [2]: Web3.isChecksumAddress('0x5B2063246f2191f18f2675cedb8b28102e957458')
Out[2]: False

In [3]: Web3.isAddress('0x5B2063246f2191f18f2675cedb8b28102e957458')
Out[3]: True
```

### How can it be fixed?

`Web3.isAddress` is a passthrough to `eth_utils.is_address`. At first glance `is_address` doesn't do anything to check the checksum. Looks like the logic just needs to be added.

**Comment by carver** [comment]
Waiting on the test update in: https://github.com/pipermerriam/web3.py/pull/235

Then will update in web3utils and here

**Comment by carver** [comment]
Waiting for the next deploy

**Comment by veox** [comment]
PR #235 has been merged.

Should be OK to close?..

**Comment by carver** [comment]
Thanks for catching this @veox
