### ISSUE TITLE
Testing errors related to `validate_address`

### ISSUE THREAD

**Issue by djrtwo** [pipermerriam/web3.py#234]
* Version: current master
* Python: 2.7/3.4/3.5
* OS: osx/linux/win

### What was wrong?

Build failing due to stricter address checksum validations from a [recent commit](https://github.com/pipermerriam/ethereum-utils/commit/ff55ae54fd7e642be324d5a001123548aa3eb5c1) in [ethereum-utils](https://github.com/pipermerriam/ethereum-utils).

### How can it be fixed?
update `validate_address` and related tests in accordance with the ethereum-utils change.

**Comment by djrtwo** [comment]
working on this now

**Comment by pipermerriam** [comment]
fixed in #235
