### ISSUE TITLE
Implement 'unit-test-mode' endpoint

### ISSUE THREAD

**Issue by pipermerriam** [pipermerriam/web3.py#24]
https://blog.ethereum.org/2016/07/08/c-dev-update-summer-edition/

Implement support for this.

**Comment by void4** [comment]
As this seems to be only available with the C++ client, we will need to:

- detect the client version with web3_clientVersion
- possibly create a new exception type (e.g. "CommandUnsupportedByClientException")
- raise this exception if an incompatible method is called

But this might not be necessary depending on how the other clients react to unknown calls.

**Comment by pipermerriam** [comment]
Not likely to happen anytime soon.
