### ISSUE TITLE
The `web3.utils.datastructures.AttributeDict` should offer an API for recursive converstion to attribute dicts.

### ISSUE THREAD

**Issue by pipermerriam** [pipermerriam/web3.py#243]
### What was wrong?

```python
>>> x = AttributeDict({'y': {'z': 3}})
>>> x.y
{'z': 3}
>>> x.y.z
AttributeError(...)
```

This behavior is correct because we don't want to *magically* convert everything because explicit is better than implicit, **but**, it would be good to have an API to allow recursive attribute dict creation.

### How can it be fixed?

New api `AttributeDict.recursive(value)` which recursively walks down into the value and converts things to attribute dicts.

This should probably be done in two pieces, a `classmethod` on the `AttributeDict` object and a stand-alone function that does the heavy lifting.

```python
import collections

from eth_utils import (
    is_dict,
    is_list_like,
)

def wrap_dicts_with_attrdict(value, _type):
    if isinstance(value, _type):
        return value
    elif is_dict(value):
        return _type({
            key: wrap_dicts_with_attrdict(item, _type)
            for key, item
            in value.items()
        })
    elif is_list_like(value) or isinstance(value, collections.Set):
        return type(value)(
            wrap_dicts_with_attrdict(item, _type) for item in value
        )
    else:
        return value
```

Then in the base class`ReadableAttributeDict` class, add a method that looks like this.

```python
class ReadableAttributeDict(...):
    @classmethod
    def recursive(cls, value):
        return wrap_dicts_with_attrdict(value, cls)
```

You will also need to write tests for this which which can be done using the simple example from above with a single nested dictionary as a starting point, and then expanding to be sure that values with nested lists, tuples, sets, strings, and integers are all converted as expected.

**Comment by carver** [comment]
There shouldn't be any circular references in normal operation, but I'll add a test for that too
