### ISSUE TITLE
Send and sign a raw Transaction with non-empty data field (as described in the docs) fails

### ISSUE THREAD

**Issue by Fefe42** [pipermerriam/web3.py#256]
* Version: 3.11.1
* Python: 3.5
* OS: Ubuntu 16.04 lts

I tried to create, sign and send a rawTransaction with a **non-empty** data field to call a function of my smart contract, as it is described here in the documentation: http://web3py.readthedocs.io/en/latest/web3.eth.html?highlight=Contract#web3.eth.Eth.sendRawTransaction

### What was wrong?

Apparently the hex value of the signed transaction was wrong and an error encountered during contract execution. I know that the value in data field was correct, because sending this data with metamask or using the sendTransaction method resulted in correct contract execution. (Here is the link of the smart contract on kovan: https://kovan.etherscan.io/address/0xd06d27e45839d25c36f084e1c19e1b5c07cf6ba8)

So I compared the signed hex value of two similar transaction and got different results. First I computed it with python then with [ethereumjs-tx](https://github.com/ethereumjs/ethereumjs-tx) 

**Python/Weby.py:**

```
>>>import rlp 
>>>from ethereum.transactions import Transaction
tx = Transaction(
    nonce=0,
    gasprice=1000,
    startgas=100000,
    to='0xd3cda913deb6f67967b99d67acdfa1712c293601',
    value=0,
    data='0x7f7465737432000000000000000000000000000000000000000000000000000000600057',
)
>>>private_key = b'e331b6d69882b4cb4ea581d88e0b604039a3de5967688d3dcffdd2270c0fd109'
>>> tx.sign(private_key)
>>> raw_tx = rlp.encode(tx)
>>> web3.toHex(raw_tx)
0xf8ad808203e8830186a094d3cda913deb6f67967b99d67acdfa1712c29360180b84a30783766373436353733373433323030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303630303035371ba0cd5a563ce737f9de5e76130f9fd61cee58c7db99275e4489165b7808fc15f3daa019e3292dfbddb55895c9626986ee1088ff30815011e1d24fc1df57e6b2376524
```

**ethereumjs-tx in nodejs:**

```
const EthereumTx = require('ethereumjs-tx')
const privateKey = Buffer.from('e331b6d69882b4cb4ea581d88e0b604039a3de5967688d3dcffdd2270c0fd109', 'hex')

const txParams = {
  nonce: '0x00',
  gasPrice: '0x3E8', 
  gasLimit: '0x186A0',
  to: '0xd3cda913deb6f67967b99d67acdfa1712c293601', 
  value: '0x00', 
  data: '0x7f7465737432000000000000000000000000000000000000000000000000000000600057',
}

const tx = new EthereumTx(txParams)
tx.sign(privateKey)
const serializedTx = tx.serialize()
console.log(serializedTx.toString('hex'))
f886808203e8830186a094d3cda913deb6f67967b99d67acdfa1712c29360180a47f74657374320000000000000000000000000000000000000000000000000000006000571ca0936dd49515125169c3e05e928b41ca93c53de2f22092b07c294aadd174412455a0741734ea413a194ec0db1d81379f14d0119b1dc2268b17ea38f31d0316cb279d
```

* If the data field is empty, the value is in python the same as in JavaScript
* I was connected to Parity 1.7, but because it is a raw Transaction this should not matter anyway.

### How can it be fixed?

I couldn't find out the reason for this behavior. It seems that the the tx.sign() or rlp.encode() are not working correctly in combination with a filled data field.

**Comment by carver** [comment]
It appears that the docs need an update, because the `Transaction` api has changed since they were written.

Try sending data as a bytes instead:

```
tx = Transaction(
    nonce=0,
    gasprice=1000,
    startgas=100000,
    to='0xd3cda913deb6f67967b99d67acdfa1712c293601',
    value=0,
    data=b'\x7ftest2\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00`\x00W',
}
```

You can get the bytes with: `Web3.toAscii('0x7f7465737432000000000000000000000000000000000000000000000000000000600057')`

**Comment by Fefe42** [comment]
Yes, it worked. Thank you very much!

I looked at https://github.com/ethereum/pyethereum/blob/develop/ethereum/transactions.py, but obviously I overread that tiny little detail ...

**Comment by sachabest** [comment]
This appears broken in the current state of the repo. If I follow these instructions exactly, I get 
```
  File "d:\code\...\env\src\web3\web3\account.py", line 180, in signTransaction
    'hash': HexBytes(transaction_hash),
  File "d:\code\...\env\src\web3\web3\utils\datastructures.py", line 181, in __new__
    bytesval = hexstr_if_str(to_bytes, val)
  File "cytoolz/functoolz.pyx", line 232, in cytoolz.functoolz.curry.__call__ (cytoolz/functoolz.c:3996)
  File "d:\code\...\env\src\web3\web3\utils\encoding.py", line 268, in hexstr_if_str
    hexstr_or_primitive,
ValueError: when sending a str, it must be a hex string. Got: '<\x9e\x8d\xdb9\xf9\n~_\xcb+\x97IOt{\x7f|\xee\xf7\xed\xa8!X\x16\x89p\xa2N\xe2\xcd\x89'
```

However, changing 
```python
return AttributeDict({
            'rawTransaction': HexBytes(rlp_encoded),
            'hash': HexBytes(transaction_hash),
            'r': HexBytes(r),
            's': HexBytes(s),
            'v': v,
        })
```
to
```python
return AttributeDict({
            'rawTransaction': to_hex(rlp_encoded),
            'hash': to_hex(transaction_hash),
            'r': to_hex(r),
            's': to_hex(s),
            'v': v,
        })
```

on line 178 of `account.py` fixes the problem for me (note I'm using python 2 even though it appears you are planning to deprecate support for it).

**Comment by carver** [comment]
> note I'm using python 2 even though it appears you are planning to deprecate support for it

Yes, Python 2 support has already been dropped on the master branch. If you want py2 support, you must use the v3 branch. (although, note that `eth.account` has not been backported to v3)

Why not upgrade to py3?

**Comment by sachabest** [comment]
Exactly my conundrum - private key signing and import is crucial to what I'm trying to do. Honestly nothing is blocking the upgrade, I just need to find the time to prioritize porting thousands of lines +
 dependencies (even with 2to3 this could take a while, no?)

In the meantime, I think adding `unicode` to all the curried type conversions that expect a `string` could mitigate this issue and preserve python2 support (with minimal code changes)

**Comment by carver** [comment]
> In the meantime, I think adding unicode to all the curried type conversions that expect a string could mitigate this issue and preserve python2 support (with minimal code changes)

This is not the only place in the code that presumes python 3 now. It's just not high on our list to backport new features to python 2. If you feel really passionate about it, and want to port the module and tests, I would accept a pull request to the `v3` branch.

> even with 2to3 this could take a while, no?

It's not zero effort, but I think you'll find 2to3 will do most of the heavy lifting. I'd be surprised if you couldn't get it done in a day or two. (not significantly more time than it would take to backport `eth.account` to py2, and maybe less time)
