### ISSUE TITLE
Undeclared dependencies: gevent and rlp

### ISSUE THREAD

**Issue by pjdelport** [pipermerriam/web3.py#26]
* Version: 1.0.0
* Python: 2.7 / 3.5
* OS: Ubuntu 16.04 LTS

### What was wrong?

On a clean installation, `import web3` fails, with import errors due to imports of `gevent` and `rlp`.

Should these be added to `install_requires`?

#### Cute Animal Picture

![kittens](http://i.imgur.com/unQLJIb.jpg)

**Comment by pipermerriam** [comment]
I'll get a fix in for this today.  Thanks for reporting.

**Comment by pipermerriam** [comment]
Fixed in `1.0.1`.  Available on `pypi` as well as in the github releases section for this repo.
