### ISSUE TITLE
Remove old "web3py" package entry from PyPI

### ISSUE THREAD

**Issue by pjdelport** [pipermerriam/web3.py#27]
### What was wrong?

As discussed on Gitter, PyPI should just have `web3`, not `web3py`.

#### Cute Animal Picture

![two bear cubs](http://i.imgur.com/KaX2fkO.jpg)

**Comment by pipermerriam** [comment]
@void4 this is going to need to be done by you as you seem to be the sole owner of that repository.

**Comment by void4** [comment]
I removed `web3py`.
