### ISSUE TITLE
How to create a contract and store / retrieve data from it?

### ISSUE THREAD

**Issue by arcade16** [pipermerriam/web3.py#276]
I have been looking through all the documentation and can't seem to find a good example of creating a basic contract and storing simple data (like a hex value or string). 

Can anyone give me the gist or point me towards a tutorial / code sample to accomplish this (relatively) simple task?

This is as far as I have gotten:
```
def eth_black_magic(hex_value):

    web3 = Web3(HTTPProvider('http://localhost:8545')) # what URL should I point at?

    user1 = 'xxx' # what goes here?
    user2  = 'xxx' # what goes here?

    transaction = {'from': user2, 'to':user1, 'data': hex_value}

    transaction_hash = web3.eth.sendTransaction(transaction)
```

**Comment by carver** [comment]
Answered the same question on stackexchange: https://ethereum.stackexchange.com/a/25522/1461

We can continue the discussion there.
