### ISSUE TITLE
When a contract call results in an empty address, return None

### ISSUE THREAD

**Issue by carver** [pipermerriam/web3.py#279]
The next step is to flesh out the specs, and building a design for review. It may or may not require py3.

### What was wrong?

If a contract returns a uint, I want it to get the return value as an `int`. If it is an address, then a value of `0x000...000` should return `None` instead, and so on. (TODO: flesh out)

One motivator is to extract the `web3utils` library from `ens.py` so ENS support can be cleanly integrated.

### How can it be fixed?

It probably means building a layer in the contract that does ABI-aware modification of the eth_call return value. At first, I was thinking middleware, but because it relies on the contract ABI, and fact that it only affects eth_call, probably means a contract-layer implementation makes the most sense.

**Comment by carver** [comment]
Ok, so for some reason, I thought this was a bigger job than it was. Really the only thing I want to change is to make 0x0 addresses return `None`.

This should happen at the end of a contract call, so a new kwarg on contract like `eth.contract(return_none=True)` seems natural. This should be a straightforward change to `normalize_return_type()`

I would just make it happen by default, but it's not backwards compatible, so that will have to wait for v4.

**Comment by pipermerriam** [comment]
I don't think it's a good idea to return `None` in place of an empty address.  Reasoning is:

* The empty address is a valid address 
* This will introduced a second semantic for the empty address meaning code will now have to both check whether its `0x0000...000` as well as `None`.  

Also gets screwy if you want to use the result of one call as the input to another call.

```python
token_A.balanceOf(contract_B.call().owner())
```

This would result in a failure if the owner of `contract_B` was the empty address....

**Comment by carver** [comment]
Ok, I'll pause advocating for this until I see how painful it is to extract out of the ENS lib. I'm not sure how many places will have this transformation required:

From
```
def resolve():
  resolver_addr = ens.resolver(namehash)
  if resolver_addr:
    resolver = Resolver(resolver_addr)
    return resolver.addr(namehash)
  else:
    return None
```

To something like:
```
def resolve():
  resolver_addr = ens.resolver(namehash)
  if Web3.toDecimal(resolver_addr):
    resolver = Resolver(resolver_addr)
    return resolver.addr(namehash)  
  else:
    return None
```
For now, it just makes me a little sad that the code won't be as elegant.

----
_But, while we're talking about it..._

I don't agree with all the implications of this:

> The empty address is a valid address

While technically valid, 0x0 _is_ a special case. Specifically, uninitialized values in the EVM start as `0x0`. Here's an example:

If you have this in Solidity:
```
// voter key voted for candidate in value:
mapping(address=>address) public votedFor;
```

Then you look up a mapping for someone who hasn't voted yet, with: `contract.votedFor(eth.accounts[0])`.

The result will be `0x0` which semantically means that the person hasn't voted yet. It doesn't mean that they voted for the candidate at address `0x0`.

I predict that there are many scenarios like this that require special casing, and the error messages that people get from passing `0x0` around without realizing it will be more confusing than the error messages from passing `None` around without realizing it.

> gets screwy if you want to use the result of one call as the input to another call.

It will get screwy anyway. In your example, it's highly unlikely that you intended to see the token balance of the null owner.

---

But as I said, I understand that it adds complexity, and at a relatively minor benefit. I'll ice it to review at a later date, with more information.

**Comment by pipermerriam** [comment]
It's less about complexity and more about whether it's a decision we should be making for our users.  I *think* that under the principle of least surprise, the expected return value is the null address (as a string).  Returning `None` is likely convenient in many cases but I don't think it should be the default, at least not for the base contract factory class.

What I would be happy to see is this implemented as a subclass of the base contract factory class that used a modified address decoder....... (hint: most of the code changes would likely need to take place in the `ethereum-abi-utils` library).

**Comment by carver** [comment]
I just went back to review, and this expectation that `0x0` means undefined (ie~ it's `__bool__` should be `False`) is really common in ENS. So even if it's not the default, I want an easy way to plug this in. You mentioned `ethereum-abi-utls`, but I think it could make at least as much sense as pluggable version of: [`web3.utils.abi.normalize_return_type()`](https://github.com/pipermerriam/web3.py/blob/master/web3/utils/abi.py#L382).

**Comment by pipermerriam** [comment]
See my comment in #312

**Comment by pipermerriam** [comment]
Also, I think you are right that this should be done at the web3 level now that I've seen your initial implementation.
