### ISSUE TITLE
Name middleware, for removing/replacing existing middleware

### ISSUE THREAD

**Issue by carver** [pipermerriam/web3.py#284]
### What was wrong?

It is difficult to modify or replace existing middleware after you add it.

### How can it be fixed?

Optionally, name the middleware at add time, like:

```
web3.add_middlware('stale-check', make_stalecheck_middleware(hours=2))
# or
web3 = Web3(..., middlewares=[caching_middleware, ('stale-check', stalecheck_middleware)])
```

Then, you can remove them individually, like:

```
web3.remove_middleware('stale-check')
# or 
web3.remove_middleware(caching_middleware)
```

Or replace with a new one:
```
web3.replace_middleware('stale-check', make_stalecheck_middleware(hours=12))
```

@pipermerriam referenced some difficulty during [our chat](https://gitter.im/pipermerriam/web3.py?at=59a9e60c210ac26920e721d5) about removing/replacing a middleware in place, because of how they're chained together. I don't understand something there, because It seems like it should be something straightforward like:

manager.py:
```
def remove(self, middleware):
    remove_idx = self._middlewares.indox(middleware)
    self._middlewares = self._middlewares[:remove_idx] + self._middewares[remove_idx + 1:]
    self._generate_request_functions()
```

(at least for the case where you are removing by the function. The name takes a bit more work)

Anyway, it will all come out in the implementation.

**Comment by carver** [comment]
So I started fiddling around with this and two items came up:

1. I'd like to change the existing tests so that the same instance of middleware can't be added twice. I think this was [agreed here](https://gitter.im/pipermerriam/web3.py?at=59a9e78f9acddb2407f31625), I just want to confirm:
> **@pipermerriam** un-named middleware just get key'd by their id(middleware_function)
2. One weirdness about adding middleware in current format is that these two end with opposite ordering:
```py
# option 1
Web3(middlewares=[a, b])
# option 2
web3.add_middleware(a)
web3.add_middleware(b)
```

Under the hood, I understand why that's happening, but it's weird. Actually, implying that people should be familiar with the `.middlewares` property at all feels kind of unnecessary. And if we take that away, then it's really confusing that the middlewares init keyword is "backwards".

**Comment by carver** [comment]
It started to feel silly to have all these `_middleware` functions. I'm thinking something like a `middleware_stack` on the web3 object, which can have whatever methods we want, like:

```
web3.middleware_stack.add()
web3.middleware_stack.remove()
web3.middleware_stack.replace()
web3.middleware_stack.clear()
```

Also, I'm not convinced we need runtime altering of the middleware stack on a provider. How about we just require users to create a new provider instance if they want to change the middleware?

I'll post a reference implementation with these ideas in code shortly.

**Comment by pipermerriam** [comment]
👍 

Feel free to take this in whatever way you feel appropriate/necessary.

**Comment by pipermerriam** [comment]
I like the `middleware_stack` name as it give semantic meaning to how the data structure behaves.
