### ISSUE TITLE
transact() might not renew transaction if called immediately

### ISSUE THREAD

**Issue by DurandA** [pipermerriam/web3.py#287]
When calling [Contract.transact](http://web3py.readthedocs.io/en/latest/contracts.html#web3.contract.Contract.transact) using `EthereumJS TestRPC v4.1.1 (ganache-core: 1.1.2)` instance with `HTTPProvider` immediatelly, it is possible that the same transaction is returned.

A simple test case is a dummy contract with a counter:
```
contract Dummy {
    uint counter = 0;

    function getAndIncrement() public constant returns(uint) {
        var temp = counter;
        counter+=1;
        return temp;
    }
}
```
Then use contract.transact().getAndIncrement() several times on a freshly deployed contract:
```
print(contract.transact({'from': coinbase}).getAndIncrement())
print(contract.transact({'from': coinbase}).getAndIncrement())
time.sleep(1)
print(contract.transact({'from': coinbase}).getAndIncrement())
print(contract.transact({'from': coinbase}).getAndIncrement())
print(contract.call().getAndIncrement())
```
Output:
```
0x81ec886b75f0732dcd4585789a49b7f27e0117502909448c9ecbbdc4498e43ea
0x81ec886b75f0732dcd4585789a49b7f27e0117502909448c9ecbbdc4498e43ea
0x84c86ca1435b6ad89d7f4a90bbb565c864a535eb6b71ff381c630816b666c717
0x84c86ca1435b6ad89d7f4a90bbb565c864a535eb6b71ff381c630816b666c717
2
```
Is this behavior correct?

**Comment by DurandA** [comment]
I close the issue as it needs further investigation. I n the meantime, I will try with another client running a local chain and eventually open an issue on TestRPC repo.

I will make sure to report back and reopen the issue if necessary.

**Comment by carver** [comment]
This might be the related issue on testrpc: https://github.com/ethereumjs/testrpc/issues/199
