### ISSUE TITLE
Implement filters as synchronous

### ISSUE THREAD

**Issue by carver** [pipermerriam/web3.py#294]
* Version: 3.11.1
* Python: 2.7
* OS: linux

### What was wrong?

This test is occasionally failing in Python 2:

```
_______________________________________________________________________________________________________ test_filter_runs_immediately ________________________________________________________________________________________________________

web3 = <web3.main.Web3 object at 0x7f08dd906b50>

    def test_filter_runs_immediately(web3):
        txn_filter = web3.eth.filter({})
        assert txn_filter.running is None
    
        txn_filter.watch(lambda _: _)
    
>       assert txn_filter.running is True
E       assert None is True
E        +  where None = <LogFilter(Thread-20, started daemon 139676051302144)>.running

txn_filter = <LogFilter(Thread-20, started daemon 139676051302144)>
web3       = <web3.main.Web3 object at 0x7f08dd906b50>

tests/core/filtering/test_filter_running_is_set_immediately.py:7: AssertionError
```

### How can it be fixed?

The async nature of filters seems to be causing the problem. Reimplement as synchronous. If someone needs async, they can provide that in a layer on top.

### Step 1

Deprecate async functionality.  Both of the following APIs should start raising deprecation warnings to notify users they are going away.

* `Filter.watch`
* `Filter.stop_watching`

### Step 2

Deprecate `Filter.get`.  It's a hard to use API that isn't intuitive.

Implement the following new APIs (names can be change).

* `Filter.get_new_entries()`: Calls the `eth_getFilterChanges` under the hood returning only the log entries that have not been returned since the last query.
* `Filter.get_all_entries()`: Calls the `eth_getFilterLogs` under the hood returning *all* matching logs for the given filter.

We should consider the following convenience APIs

* `Filter.reset()`: Uninstalls and then reinstalls the filter.
* `Filter.uninstall()`: Uninstalls the filter.

### Step 3

Remove the deprecated APIs (this should be at least 1-2 months after the first release that the api was deprecated to give people time to upgrade.

### Suggested examples for documentation

* How to wrap a filter in a thread.
* How to *listen* for new pending transactions.
* How to *listen* for newly mined blocks.
* How to *manually* filter for log entries (not using a contract)
* How to filter for a `Contract` instance's log entries.

**Comment by pipermerriam** [comment]
Lets be sure to include an example in the documentation of how someone would do this with the built in threading or multiprocessing libraries.

**Comment by djrtwo** [comment]
Are we keeping a very similar API for maximum backwards compatibility, but removing all GreenletThread and ansyncronous related code?

Example keeping call to `watch` but removing `stop_watching`.
Having `watch` explicitly call a modified version of `_run`, etc.

**Comment by carver** [comment]
@djrtwo Since steps 1 & 2 involve perfect backwards compatibility, I assume you're talking about step 3.

> removing all GreenletThread ... code?

Completely removing gevent support is a goal: #251 . It may be possible to kill two issues with one PR.

> removing all ... ansyncronous related code?

My first instinct is to remove all asynchronous code. That means we should show people how to implement `watch` in their own projects (in new docs), but not provide the method. If we keep `watch` at all, we're kind of back where we started: with an asynchronous method that people have a hard time catching errors in.

**Comment by djrtwo** [comment]
The comment was before piper cleared up with those steps. I'm on the right
track now. Thanks!

**Comment by carver** [comment]
@djrtwo Anything I can do to help?

If this ended up being too big, maybe we can cut it down to a better size. I ended up doing that recently: cutting the code down significantly twice, because there was just too much to reasonably cover in one PR (both for author and reviewer).

**Comment by carver** [comment]
Will be released with v4 beta, soon<sup>TM</sup>
