### ISSUE TITLE
Implement the upcoming web3.js `web3.eth.accounts` API

### ISSUE THREAD

**Issue by carver** [pipermerriam/web3.py#323]
### What was wrong?

There is no good API for local key manipulation and signing.

### How can it be fixed?

The new [eth_keys](https://github.com/pipermerriam/ethereum-keys) package should be able to handle most of the implementation of actually manipulating keys and signing with them.

The proposed v1 API of [`web3.eth.accounts`](https://web3js.readthedocs.io/en/1.0/web3-eth-accounts.html) in web3.js seems reasonable. Let's implement it.

Out of scope for this particular issue (but probably reasonable to consider in the future):

* [`accounts.wallet.*`](https://web3js.readthedocs.io/en/1.0/web3-eth-accounts.html#wallet) - "Contains an in memory wallet with multiple accounts"

**Comment by pipermerriam** [comment]
The `accounts.encrypt` and `accounts.decrypt` code is already written in [`eth_keyfile`](https://pypi.python.org/pypi/ethereum-keyfile).  You just have to hook in to the existing functions.

**Comment by carver** [comment]
Nice, I'll put those in scope then.

**Comment by carver** [comment]
Merged into master
