### ISSUE TITLE
getData function implementation

### ISSUE THREAD

**Issue by bellaj** [pipermerriam/web3.py#345]
I am wondering if the getData (from web3js) is implemented in web3.py.

```
// Get the call data, so you can call the contract through some other means
var myCallData = myContractInstance.myMethod.getData(param1 [, param2, ...]);
// myCallData = '0x45ff3ff6000000000004545345345345..'
```
 I was trying to create a rawtransaction with contract's function call using getdata. Is there any alternative?

**Comment by pipermerriam** [comment]
@bellaj you should be able to do the following.

```python
call_data = my_contract_instance.encodeABI(fn_name='someFunction', args=[param1, param2], kwargs={'param3': param3})
```

The `call_data` value will have the function selector at the beginning followed by the abi encoded parameters for calling the function.

**Comment by pipermerriam** [comment]
If you want *only* the encoded parameters without the function selector, add an extra keyword argument `data=b''` to the call.

**Comment by bellaj** [comment]
Thank you @pipermerriam for the hint.
