### ISSUE TITLE
PyPI 3.16.2 version is not up to date

### ISSUE THREAD

**Issue by RetardVeverca** [pipermerriam/web3.py#362]
* Version: 3.16.2
* Python: 2.7
* OS: osx

### What was wrong?

Version uploaded to pip (https://pypi.python.org/pypi/web3/3.16.2) is not the same as in this repo. They are both 3.16.2, but pip source code does not include all the changes. web3.eth.account (account.py) is missing for example ....

### How can it be fixed?

Source on PyPI should be updated

**Comment by carver** [comment]
@RetardVeverca The `master` branch is being prepared for v4. To see the latest commits for versions 3.*, see the `v3` branch.

See #336 for more background

**Comment by RetardVeverca** [comment]
Ah I see, thank you for making it clear. Keep up the great work ;)
