### ISSUE TITLE
Expose _Contract

### ISSUE THREAD

**Issue by miohtama** [pipermerriam/web3.py#37]
### What was wrong?

Currently `web3.contract._Contract` is privateish It would be useful to expose this for static analysis to help IDE auto completion.

I'd suggest renaming `_Contract` to `Contract` or `ContractBase` and then exposing it in necessary `__init__` modules.

#### Cute Animal Picture

![moo](http://i.imgur.com/2lXkjxH.jpg)

**Comment by pipermerriam** [comment]
I'm fine with just renaming this class to `Contract` and would prefer that over an `import X as Y` rename.
