### ISSUE TITLE
Filter.get_all_entries() not returning events within specified block range

### ISSUE THREAD

**Issue by Avios64** [pipermerriam/web3.py#398]
* Version: 3.16.1
* Python: 3.6.2
* OS: win

### What was wrong?

The below code returns no results for events registered during that block range, have tried with both .get_all_entries() and .get(). I have removed the ABI for readability. 

`address_registrar = "0x6090A6e47849629b7245Dfa1Ca21D94cd15878Ef"`  
 `ens_registrar_contract = web3_obj.eth.contract(abi=ERC20_abi_registrar, address=address_registrar)`  
 `ens_filter = ens_registrar_contract.pastEvents("HashRegistered", {"fromBlock": 3997260, "toBlock": 
 3997270})`  
` results = ens_filter.get_all_entries()`

Smart contract code that registers the event:

` function finalizeAuction(bytes32 _hash) onlyOwner(_hash) {`
        `entry h = _entries[_hash];`
    `h.value =  max(h.value, minPrice);`
       `h.deed.setBalance(h.value, true);`
       `trySetSubnodeOwner(_hash, h.deed.owner());`
        `HashRegistered(_hash, h.deed.owner(), h.value, h.registrationDate);`
    `}`

As the block range is 3997260 - 3997270, I expect to receive the event for https://etherscan.io/tx/0x05712456eca3acb77a524960757240088af05f0ddb2a4fb2a7cd6d8fb2a8880f registered at blockNum 3997264

Changing the "fromBlock" to <3997257 will return the event.

Running the following node:

`Geth`
`Version: 1.7.2-stable`
`Git Commit: 1db4ecdc0b9e828ff65777fb466fc7c1d04e0de9`
`Architecture: amd64`
`Protocol Versions: [63 62]`
`Network Id: 1`
`Go Version: go1.9`
`Operating System: windows`

**Comment by pipermerriam** [comment]
ok, I've verified this behavior.  This *looks* a lot like a bug in geth.  Going to try and chase down with the go-ethereum team.

**Comment by pipermerriam** [comment]
https://github.com/ethereum/go-ethereum/issues/15404

**Comment by pipermerriam** [comment]
@Avios64 it was indeed a go-ethereum bug which will be fixed in the next release of go-ethereum.
