### ISSUE TITLE
AttributeError: 'Eth' object has no attribute 'account'

### ISSUE THREAD

**Issue by kuramameng** [pipermerriam/web3.py#410]
* Version: 3.16.2
* Python: 2.7
* OS: linux

running w3.eth.account.create('KEYSMASH FJAFJKLDSKF7JKFDJ 1530') from the documentation gives the following error:

AttributeError: 'Eth' object has no attribute 'account'

**Comment by carver** [comment]
`w3.eth.account` is only available in v4 which has not reached beta release, yet. (hopefully it will in a week or two)

You can install web3 from the master branch to get access immediately, but the module is still in flux. Alternatively, you can see the docs for v3 at: http://web3py.readthedocs.io/en/stable/ (which doesn't include the eth.account module at all)
