### ISSUE TITLE
Why ethereum-keyfile not in requirements-dev.txt?

### ISSUE THREAD

**Issue by SlavikDMI** [pipermerriam/web3.py#418]
I tried import web3.account, but had an error: 
.....web3/account.py", line 13, in <module>
    from eth_keyfile import (
ImportError: No module named 'eth_keyfile'
and after that: File "......./web3/account.py", line 31, in <module>
    from web3.utils.datastructures import (
ImportError: cannot import name 'HexBytes'

**Comment by carver** [comment]
`requirements-dev.txt` holds the extra requirements for development. To get the core requirements, run `pip install -e .`

See https://github.com/pipermerriam/web3.py#developer-setup

If that doesn't resolve the issue for you, please reopen.
