### ISSUE TITLE
is it possible to send in functions bytes32?

### ISSUE THREAD

**Issue by SlavikDMI** [pipermerriam/web3.py#422]
How convert string in python to bytes32 format?

**Comment by pipermerriam** [comment]
@SlavikDMI can you please provide some code that highlights what you are trying to do?  do you have a contract instance you are interacting with?

**Comment by SlavikDMI** [comment]
`pragma solidity ^0.4.16;

contract A  {

    address name;
    bytes10 public  hash; 
    bytes10 public hash2;
    function A(bytes10 _hash2) {
        hash2 = _hash2;
         hash = bytes10(keccak256(msg.sender));  
        
    }
}`


hash is -  bytes10: 0xb1591967aed668a4b276

but when i write "0xb1591967aed668a4b276" as value in constructor , it cause error.
BUT, if i write value <= 10 ,it is ok.
bytes10 != len(10) but how send bytes10 ?
when i write '0xb1591967aed668a4b276'
TypeError: One or more arguments could not be encoded to the necessary ABI type.  Expected types are: bytes10
when '0xb159' its ok

**Comment by carver** [comment]
@SlavikDMI I assume you're using web3 v3, right?

The functionality here will change in v4 to work the way you expected. Until then, you can convert your hex string into bytes before calling the function, using:

```
constructor_arg = Web3.toBytes(hexstr="0xb1591967aed668a4b276")
```

**Comment by SlavikDMI** [comment]
v4 of do you mean? 
I'll try your tip
