### ISSUE TITLE
Calling any solidity function returning address[ ] gives address list without 0x prefix

### ISSUE THREAD

**Issue by agatsoh** [pipermerriam/web3.py#70]
* Version: 1.8.0
* Python: 2.7.6
* OS: Ubuntu 14.04

### What was wrong?
Calling any solidity function returning address[ ] gives address list without 0x prefix

#### Cute Animal Picture
![image](https://cloud.githubusercontent.com/assets/15123108/18062197/729941c8-6e43-11e6-8683-8598b1979f89.png)

![Cute animal picture]()

**Comment by pipermerriam** [comment]
This is happening here https://github.com/pipermerriam/web3.py/blob/master/web3/contract.py#L633

That functionality should probably be extracted into something small that recursively calls into itself if it's dealing with `array` types.

**Comment by pipermerriam** [comment]
Loosely, I think the solution for this looks like the following.

```python
from eth_abi.abi import (
    process_type,
 )

def normalize_return_type(data_type, data_value):
    base, _, arrlist = process_type(data_type)
    if arrlist:
        sub_type = (base, sub, arrlist[:-1])
        return [normalize_return_type(sub_type, sub_value) for sub_value in data_value]
    elif base == 'address':
        return add_0x_prefix(data_value)
    else:
        return data_value
    
# Over in `contract.py`   
normalized_data = normalize_return_type(output_types, output_data)
```
