### ISSUE TITLE
deplying empty contract

### ISSUE THREAD

**Issue by shayanb** [pipermerriam/web3.py#95]
* Version: 2.7.1
* Python: 2.7
* OS: osx

### What was wrong?
I used this code to deploy new contracts
```
    abi_json = json.loads(abi)
    ContractFactory = web3rpc.eth.contract(abi_json, code=bytesource)
    txhash = ContractFactory.deploy()
```
It used to work for a while till around 2 weeks ago it just deploys empty contracts. I've tried changing everything on my ABI and bytecode (e.g adding 0x in from of the bytecode) but nothing seems to fix it. Any ideas why this might happen? any incompatibility with new geth update?

**Comment by pipermerriam** [comment]
Can you provide some more detail on exactly what is going wrong?  How exactly is this operation failing?

**Comment by shayanb** [comment]
Not sure what was the issue but it was deploying empty contacts last week (data = 0x) but now that I tried it worked fine! 
I'll keep you posted if I could figure out what happened there.

**Comment by pipermerriam** [comment]
no problem.  Feel free to reach out to me on gitter as well.
